import Link from "next/link";
import { BarChart3, BookOpen, Building2, CreditCard, FileText, Landmark, ReceiptText, Settings, Upload, WalletCards } from "lucide-react";
import { UserSessionStatus } from "@/components/user-session-status";

const links = [["Tổng quan", "/accounts", BarChart3], ["Đối chiếu ngân hàng", "/accounts/bank-reconciliation", Landmark], ["Nhập sao kê", "/accounts/statement-imports", Upload], ["Tài khoản ngân hàng", "/accounts/bank-accounts", WalletCards], ["Ngân hàng", "/accounts/banks", Building2], ["Giao dịch ngân hàng", "/accounts/bank-transactions", BarChart3], ["Quy tắc matching", "/accounts/bank-transaction-rules", Settings], ["Cấu hình kế toán", "/accounts/settings", Settings], ["Trung tâm chi phí", "/accounts/cost-centers", BookOpen], ["Journal Entry", "/accounts/journal-entries", FileText], ["Hóa đơn", "/accounts/purchase-invoices", ReceiptText], ["Thanh toán", "/accounts/payment-entries", CreditCard], ["Báo cáo", "/accounts/reports", Landmark]] as const;

export async function AccountingShell({ children }: Readonly<{ children: React.ReactNode }>) {
  return <div className="flex min-h-screen bg-muted/30"><aside className="hidden w-64 shrink-0 border-r bg-slate-950 text-slate-300 md:block"><div className="flex h-16 items-center gap-3 border-b border-slate-800 px-5 text-sm font-bold tracking-[0.18em] text-white"><span className="grid size-8 place-items-center rounded-lg bg-blue-600 tracking-normal">L</span>LeTRON</div><div className="px-4 py-6"><p className="mb-3 px-2 text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500">LeTRON-Kế toán</p><nav className="space-y-1" aria-label="Điều hướng kế toán">{links.map(([label, href, Icon]) => <Link className="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm text-slate-400 hover:bg-slate-900 hover:text-white" href={href} key={label}><Icon className="size-4" />{label}</Link>)}</nav></div><div className="absolute bottom-0 w-64 border-t border-slate-800 px-6 py-4 text-xs text-slate-500"><span className="block">LeTRON-Global Portal SSO</span><form action="/api/auth/logout" method="post"><button className="mt-2 text-slate-400 underline hover:text-white" type="submit">Đăng xuất</button></form></div></aside><div className="min-w-0 flex-1"><header className="flex h-16 items-center justify-between border-b bg-background px-5 md:px-8"><span className="text-sm font-semibold">LeTRON-Kế toán</span><div className="flex items-center gap-3"><span className="hidden rounded-full bg-muted px-3 py-1.5 text-xs text-muted-foreground sm:inline">Accounting workspace</span><UserSessionStatus /></div></header>{children}</div></div>;
}
