"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { clientQuery } from "@/lib/client-query";
import type { AccountingFormField, AssetResource } from "@/lib/letron-api";

export function AssetRecordForm({ resource, fields, initial, name }: Readonly<{ resource: AssetResource; fields: AccountingFormField[]; initial?: Record<string, unknown>; name?: string }>) {
  const router = useRouter(); const queryClient = useQueryClient();
  const [values, setValues] = useState<Record<string, string | boolean>>(() => Object.fromEntries(fields.map((field) => [field.name, field.type === "boolean" ? Boolean(initial?.[field.name]) : field.type === "array" ? JSON.stringify(initial?.[field.name] ?? [], null, 2) : initial?.[field.name] == null ? "" : String(initial[field.name])] )));
  const [error, setError] = useState<string | null>(null);
  const mutation = useMutation({ mutationFn: ({ endpoint, payload }: { endpoint: string; payload: Record<string, unknown> }) => clientQuery<{ name?: string }>(endpoint, { method: name ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }), onSuccess: async (data) => { await queryClient.invalidateQueries({ queryKey: ["assets", resource] }); const created = data?.name; router.push(created ? `/assets/${resource}/${encodeURIComponent(created)}` : `/assets/${resource}`); router.refresh(); } });
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); const payload: Record<string, unknown> = {}; for (const field of fields) { const value = values[field.name]; if (field.required && (value === "" || value === undefined)) { setError(`${field.name} is required`); return; } if (value === "" || value === undefined) continue; if (field.type === "boolean") payload[field.name] = value; else if (field.type === "number" || field.type === "integer") payload[field.name] = Number(value); else if (field.type === "array") { try { payload[field.name] = JSON.parse(String(value)); } catch { setError(`${field.name} must contain valid JSON`); return; } } else payload[field.name] = value; } try { await mutation.mutateAsync({ endpoint: `/api/assets/${resource}${name ? `/${encodeURIComponent(name)}` : ""}`, payload }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Save failed"); } }
  return <form className="space-y-6 rounded-xl border bg-card p-5 shadow-sm" onSubmit={submit}><div className="grid gap-5 md:grid-cols-2">{fields.map((field) => <div className={field.type === "array" ? "space-y-2 md:col-span-2" : "space-y-2"} key={field.name}><Label htmlFor={field.name}>{field.name.replaceAll("_", " ")}{field.required ? " *" : ""}</Label>{field.type === "boolean" ? <input className="size-4 accent-emerald-600" id={field.name} type="checkbox" checked={Boolean(values[field.name])} onChange={(event) => setValues((current) => ({ ...current, [field.name]: event.target.checked }))} /> : field.enum?.length ? <select className="flex h-10 w-full rounded-md border bg-background px-3 text-sm" id={field.name} value={String(values[field.name] ?? "")} onChange={(event) => setValues((current) => ({ ...current, [field.name]: event.target.value }))}><option value="">Select...</option>{field.enum.map((option) => <option key={option} value={option}>{option}</option>)}</select> : field.type === "array" ? <Textarea id={field.name} rows={8} value={String(values[field.name] ?? "")} onChange={(event) => setValues((current) => ({ ...current, [field.name]: event.target.value }))} /> : <Input id={field.name} type={field.format === "date" ? "date" : field.type === "number" || field.type === "integer" ? "number" : "text"} value={String(values[field.name] ?? "")} onChange={(event) => setValues((current) => ({ ...current, [field.name]: event.target.value }))} />}{field.targetDoctype ? <p className="text-xs text-muted-foreground">Link: {field.targetDoctype}</p> : null}</div>)}</div>{error ? <p className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p> : null}<Button disabled={mutation.isPending} type="submit">{mutation.isPending ? "Saving..." : name ? "Save changes" : "Create record"}</Button></form>;
}
