import { Suspense } from "react";
import { Building2 } from "lucide-react";

import { AppSidebarNav } from "@/components/app-sidebar-nav";
import { UserSessionStatus } from "@/components/user-session-status";

const links = [["Tổng quan", "/assets", "BarChart3"], ["Tài sản", "/assets/assets", "Archive"], ["Nhóm tài sản", "/assets/asset-categories", "Box"], ["Asset Capitalization", "/assets/asset-capitalizations", "ClipboardList"], ["Bảo trì", "/assets/asset-maintenance", "Wrench"], ["Điều chuyển", "/assets/asset-movements", "Cog"], ["Sửa chữa", "/assets/asset-repairs", "Wrench"], ["Điều chỉnh giá trị", "/assets/asset-value-adjustments", "BarChart3"], ["Địa điểm", "/assets/locations", "MapPin"], ["Đội bảo trì", "/assets/asset-maintenance-teams", "Users"], ["Nhật ký bảo trì", "/assets/asset-maintenance-logs", "ClipboardList"], ["Lịch khấu hao", "/assets/asset-depreciation-schedules", "BarChart3"], ["Hệ số ca", "/assets/asset-shift-factors", "Cog"], ["Phân bổ ca", "/assets/asset-shift-allocations", "Cog"], ["Báo cáo", "/assets/reports", "FileBarChart"], ["Dashboard", "/assets/dashboard", "BarChart3"]] as const;

export function AssetsAppShell({ children }: Readonly<{ children: React.ReactNode }>) {
  return <div className="flex min-h-screen bg-muted/30"><aside className="hidden w-64 shrink-0 border-r bg-emerald-950 text-emerald-100 md:block"><div className="flex h-16 items-center gap-3 border-b border-emerald-900 px-5 text-sm font-bold tracking-[0.18em] text-white"><span className="grid size-8 place-items-center rounded-lg bg-emerald-600 tracking-normal">L</span>LeTRON</div><div className="px-4 py-6"><p className="mb-3 px-2 text-[10px] font-bold uppercase tracking-[0.18em] text-emerald-400">LeTRON-Tài sản</p><AppSidebarNav items={links} label="Điều hướng tài sản" tone="emerald" /></div><div className="absolute bottom-0 w-64 border-t border-emerald-900 px-6 py-4 text-xs text-emerald-400"><span className="block">Letron Assets</span><form action="/api/auth/logout?return_to=%2Fassets" method="post"><button className="mt-2 rounded-sm underline outline-none hover:text-white focus-visible:ring-2 focus-visible:ring-emerald-400" type="submit">Đăng xuất</button></form></div></aside><div className="min-w-0 flex-1"><header className="flex h-16 items-center justify-between border-b bg-background px-5 md:px-8"><span className="flex items-center gap-2 text-sm font-semibold"><Building2 className="size-4 text-emerald-700" />LeTRON-Tài sản</span><div className="flex items-center gap-3"><span className="hidden rounded-full bg-emerald-50 px-3 py-1.5 text-xs text-emerald-700 sm:inline">Asset workspace</span><Suspense fallback={<span className="inline-flex h-8 w-24 animate-pulse rounded-full bg-emerald-100" aria-label="Đang tải phiên đăng nhập" />}><UserSessionStatus returnTo="/assets" /></Suspense></div></header>{children}</div></div>;
}
