"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { clientQuery } from "@/lib/client-query";
import { createWarehouseRequestSchema, updateWarehouseRequestSchema } from "@/generated/zod";
type Row = Record<string, unknown>;
export function WarehouseForm({ initial, warehouses, basePath = "/stock" }: Readonly<{ initial?: Row; warehouses: Row[]; basePath?: string }>) {
  const router = useRouter(); const [values, setValues] = useState<Row>({ warehouse_name: "", company: "", parent_warehouse: "", warehouse_type: "", is_group: false, disabled: false, ...initial }); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const set = (key: string, value: unknown) => setValues((current) => ({ ...current, [key]: value }));
  async function save(event: React.FormEvent) { event.preventDefault(); if (saving) return; setSaving(true); setError(null); try { const payload = { ...values, parent_warehouse: values.parent_warehouse || undefined, warehouse_type: values.warehouse_type || undefined }; (initial ? updateWarehouseRequestSchema : createWarehouseRequestSchema).parse(payload); const saved = await clientQuery<Row>(`/api/stock/warehouses${initial?.name ? `/${encodeURIComponent(String(initial.name))}` : ""}`, { method: initial ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); router.push(`${basePath}/warehouses/${encodeURIComponent(String(saved.name ?? initial?.name ?? ""))}`); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể lưu Warehouse."); } finally { setSaving(false); } }
  return <form className="space-y-5 rounded-xl border bg-card p-5 shadow-sm" onSubmit={(event) => void save(event)}><div className="grid gap-4 md:grid-cols-2"><div><Label htmlFor="warehouse_name">Tên Warehouse *</Label><Input id="warehouse_name" required value={String(values.warehouse_name ?? "")} onChange={(event) => set("warehouse_name", event.target.value)} /></div><div><Label htmlFor="company">Company *</Label><Input id="company" required value={String(values.company ?? "")} onChange={(event) => set("company", event.target.value)} /></div><div><Label htmlFor="parent_warehouse">Warehouse cha</Label><select id="parent_warehouse" className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm" value={String(values.parent_warehouse ?? "")} onChange={(event) => set("parent_warehouse", event.target.value)}><option value="">Không có</option>{warehouses.filter((row) => row.name !== initial?.name).map((row) => <option key={String(row.name)} value={String(row.name)}>{String(row.warehouse_name ?? row.name)}</option>)}</select></div><div><Label htmlFor="warehouse_type">Loại Warehouse</Label><Input id="warehouse_type" value={String(values.warehouse_type ?? "")} onChange={(event) => set("warehouse_type", event.target.value)} /></div></div><div className="flex gap-6"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(values.is_group)} onChange={(event) => set("is_group", event.target.checked)} /> Kho nhóm</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(values.disabled)} onChange={(event) => set("disabled", event.target.checked)} /> Vô hiệu hóa</label></div>{error ? <p className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p> : null}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => router.back()}>Hủy</Button><Button disabled={saving} type="submit">{saving ? "Đang lưu..." : initial ? "Lưu thay đổi" : "Tạo Warehouse"}</Button></div></form>;
}
