import Link from "next/link";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { AlertCircle } from "lucide-react";
import { StockTable } from "@/components/stock-table";
import { ResourcePagination } from "@/components/resource-pagination";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { GatewayAccessDeniedError, GatewayAuthenticationRequiredError, listStockResource, RESOURCE_PAGE_SIZE } from "@/lib/letron-api";
import { larkLoginHref } from "@/lib/auth-navigation";

export const dynamic = "force-dynamic";
export default async function WarehousesPage({ searchParams }: { searchParams: Promise<{ page?: string; q?: string }> }) { const params = await searchParams; const page = Math.max(1, Number.parseInt(params.page ?? "1", 10) || 1); const q = (params.q ?? "").trim(); const returnTo = `/stock/warehouses${page > 1 || q ? `?${new URLSearchParams({ ...(q ? { q } : {}), ...(page > 1 ? { page: String(page) } : {}) })}` : ""}`; let rows: Record<string, unknown>[] = []; let error: string | null = null; let denied = false; let hasNext = false; try { const query = new URLSearchParams({ limit_page_length: String(RESOURCE_PAGE_SIZE + 1), limit_start: String((page - 1) * RESOURCE_PAGE_SIZE) }); if (q) query.set("filters", JSON.stringify([["Warehouse", "warehouse_name", "like", `%${q}%`]])); rows = await listStockResource("warehouses", (await cookies()).toString(), query.toString()); hasNext = rows.length > RESOURCE_PAGE_SIZE; rows = rows.slice(0, RESOURCE_PAGE_SIZE); } catch (cause) { if (cause instanceof GatewayAuthenticationRequiredError) redirect(larkLoginHref(returnTo)); denied = cause instanceof GatewayAccessDeniedError; error = cause instanceof Error ? cause.message : "Không thể kết nối Gateway."; } return <main className="mx-auto max-w-7xl space-y-6 p-5 md:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Stock / WH-01</div><h1 className="text-3xl font-bold tracking-tight">Warehouse</h1><p className="mt-2 text-muted-foreground">Kho tham chiếu cho các dòng Purchase Receipt.</p></div><Button asChild><Link href="/stock/warehouses/new">Tạo Warehouse</Link></Button></div><form className="flex gap-2" method="get"><input className="h-10 flex-1 rounded-md border bg-background px-3 text-sm" name="q" placeholder="Tìm Warehouse..." defaultValue={q} /><Button variant="outline" type="submit">Tìm kiếm</Button></form>{error ? <Alert variant="destructive"><AlertCircle className="size-4" /><AlertTitle>{denied ? "Chưa được cấp quyền" : "Không lấy được dữ liệu"}</AlertTitle><AlertDescription>{error}</AlertDescription></Alert> : <><StockTable resource="warehouses" rows={rows} />{rows.length || page > 1 ? <ResourcePagination basePath="/stock/warehouses" query={q ? `q=${encodeURIComponent(q)}` : ""} page={page} hasNext={hasNext} tone="emerald" /> : null}</>}</main>; }
